### ISSUE TITLE
Add Hidden option to Column Config

### ISSUE THREAD

**Issue by paugnu** [hyva-themes/magento2-hyva-admin#10] opened 2021-01-12 18:58 UTC
Hi,

I think it might be interesting to add a new Column Config option: isHidden (note that this is different from 'Exclude'). 

The idea is to have the column available to be displayed, but not visible by default.

I'll try to implement this myself, I have a lot to learn though :)

**Comment by Vinai** [comment] 2021-01-12 21:42
Thanks for your suggestion, makes sense.
This is interesting because the column property from the grid XML influences the initial settings for the JS Display dropdowns.
If you want to continue, let me know please if you have specific questions regarding the implementation.
Should you run out of time or motivation though, no problem :)
I or someone else can pick up the issue.

**Comment by Vinai** [comment] 2021-01-12 21:43
Duplicate of #11

**Closed by Vinai** 2021-01-12 21:43 UTC
Labels: enhancement
